name: Pandoc
on:
    push:
      branch:
        - master
    pull_request:
      branch:
        - master
  
jobs:
  pandoc_conversion:
    runs-on: ubuntu-18.04
    steps:
      # Checkout
      - name: checkout
        uses: actions/checkout@v2
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/about.md -o html/about.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/annoucements.md -o html/annoucements.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/citation.md -o html/citation.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/contact.md -o html/contact.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/publications.md -o html/publications.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/related-resources.md -o html/related-resources.html'
      # Run Pandoc
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: '-f gfm -t html pages/team.md -o html/team.html'
      # Commit 
      - name: commit
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./html
          git commit -m "Add changes"
      # Push Changes
      - name: push
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
